version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    expose:
      - 3000
    environment:
      - YAPI_ADMIN_ACCOUNT=${YAPI_ADMIN_ACCOUNT}
      - YAPI_ADMIN_PASSWORD=${YAPI_ADMIN_PASSWORD}
      - YAPI_CLOSE_REGISTER=${YAPI_CLOSE_REGISTER}
      - YAPI_DB_SERVERNAME=${YAPI_DB_SERVERNAME}
      - YAPI_DB_PORT=${YAPI_DB_PORT}
      - YAPI_DB_DATABASE=${YAPI_DB_DATABASE}
      - YAPI_MAIL_ENABLE=${YAPI_MAIL_ENABLE}
      - YAPI_LDAP_LOGIN_ENABLE=${YAPI_LDAP_LOGIN_ENABLE}
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
    networks:
      - default
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
    networks:
     - default
  nginx:
    image: nginx:1.22.0-alpine
    ports:
      - "80:80"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default
